In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split as tts, GridSearchCV, cross_val_score

#Scale between -1 to 1 for avoiding hude distant number comparison giving bad results
from sklearn.preprocessing import StandardScaler

#Classifier
from sklearn.neighbors import KNeighborsClassifier

#Testing tools
from sklearn.metrics import confusion_matrix
from sklearn.metrics import f1_score
from sklearn.metrics import accuracy_score

In [2]:
df = pd.read_csv('data/breast_cancer.csv')
#df.head()
print(len(df))

569


In [3]:
df.isna().sum()

id                           0
diagnosis                    0
radius_mean                  0
texture_mean                 0
perimeter_mean               0
area_mean                    0
smoothness_mean              0
compactness_mean             0
concavity_mean               0
concave points_mean          0
symmetry_mean                0
fractal_dimension_mean       0
radius_se                    0
texture_se                   0
perimeter_se                 0
area_se                      0
smoothness_se                0
compactness_se               0
concavity_se                 0
concave points_se            0
symmetry_se                  0
fractal_dimension_se         0
radius_worst                 0
texture_worst                0
perimeter_worst              0
area_worst                   0
smoothness_worst             0
compactness_worst            0
concavity_worst              0
concave points_worst         0
symmetry_worst               0
fractal_dimension_worst      0
Unnamed:

In [4]:
#splitting the dataset
X = df.iloc[:, 2:-1]  #excluded first second and last columns which had indexs, nulls and our y
y = df.iloc[:, 1]
#print(X)
#print(y)

In [5]:

from numpy import argmax
from sklearn.preprocessing import LabelEncoder
values = y
# integer encode
label_encoder = LabelEncoder()
integer_encoded = label_encoder.fit_transform(values)
y = pd.Series(integer_encoded)


In [6]:
#splitting the dataset
X_train, X_test, y_train, y_test = tts(X, y, random_state = 42, test_size=0.2)

In [7]:
#print(X_train)
#print(X_test)
#print(y_train)
#print(y_test)

In [8]:
#feature scaling
sc_X = StandardScaler()

#We will train and transform X_train 
X_train = sc_X.fit_transform(X_train)

#We will only transform X_test no training... what difference tho?
X_test = sc_X.transform(X_test)

In [9]:
#checking mean for neighbors
import math
_dataMean = round(math.sqrt(len(y_train)))
_dataMean

21

---------------------------GridSearchCV---------------------------------------

In [10]:
#initializing an empty Model

knn_c = KNeighborsClassifier()

In [11]:
knn_c.fit(X_train, y_train)


KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=5, p=2,
           weights='uniform')

In [12]:

knn_c.score(X_test, y_test)

0.9473684210526315

In [13]:
#setting params set
params = {'n_neighbors':np.arange(1,_dataMean,1),  "metric":["euclidean", "minkowski", "jaccard", "cosine"]}

In [14]:
#cross validation for some prediction. what difference does it makes!
cross_val_score(knn_c, X,y, cv=10)

array([0.9137931 , 0.87931034, 0.89473684, 0.96491228, 0.94736842,
       0.92982456, 0.96491228, 0.92857143, 0.91071429, 0.96428571])

In [15]:
max(cross_val_score(knn_c, X,y, cv=10))

0.9649122807017544

In [16]:
knn_cv = GridSearchCV(estimator=knn_c, param_grid=params, cv=10)

In [17]:
knn_cv.fit(X, y)

C:\Users\sahrunnisha\Anaconda3\lib\site-packages\sklearn\model_selection\_search.py:841: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)


GridSearchCV(cv=10, error_score='raise-deprecating',
       estimator=KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=5, p=2,
           weights='uniform'),
       fit_params=None, iid='warn', n_jobs=None,
       param_grid={'n_neighbors': array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20]), 'metric': ['euclidean', 'minkowski', 'jaccard', 'cosine']},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring=None, verbose=0)

In [18]:
knn_cv.best_score_

0.9332161687170475

In [19]:
knn_cv.best_params_

{'metric': 'euclidean', 'n_neighbors': 14}

In [20]:
knn_cv.best_estimator_

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='euclidean',
           metric_params=None, n_jobs=None, n_neighbors=14, p=2,
           weights='uniform')

---------------------------Manually Setting the model---------------------

In [21]:
classifier = KNeighborsClassifier(n_neighbors=_dataMean, p=2, metric='euclidean')

In [22]:
classifier.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='euclidean',
           metric_params=None, n_jobs=None, n_neighbors=21, p=2,
           weights='uniform')

In [23]:
#cross validation for some prediction idk what!
max(cross_val_score(classifier, X,y, cv=10))

0.9649122807017544

In [24]:
#PRedicting Test set results
y_pred = classifier.predict(X_test)
y_pred

array([0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0,
       1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 1])

In [25]:
#confusion matric 
cm = confusion_matrix(y_test, y_pred)
print(cm)
#In confusion matric second diagonal means right prediction count and vice-versa 

[[69  2]
 [ 4 39]]


In [26]:
#pos_label sets the positive standard/class for computation incase of non integer y
#print(f1_score(y_test, y_pred, pos_label='M'))
print(f1_score(y_test, y_pred))


0.9285714285714286


In [27]:
print(accuracy_score(y_test, y_pred))

0.9473684210526315
